/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    NAnchor: typeof import('naive-ui')['NAnchor']
    NAnchorLink: typeof import('naive-ui')['NAnchorLink']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NIcon: typeof import('naive-ui')['NIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
